#!/bin/bash

FILENAME=$1
CODEFILENAME="${FILENAME}.c"

rm $FILENAME -f

echo $FILENAME

if gcc -Wall -o $FILENAME $CODEFILENAME; then
./$FILENAME;
else
echo "Compilation Error";
fi 

#no terminal basta ./CX ex2 e funciona; 
#$ chmod +x hello.sh --> antes fiz isto por causa das premissões